web:
  image: php:5.6.25-apache
#  image: mdnmdn/php-7.0.13-apache
#  image: mdnmdn/php-5.6-apache
  container_name: web-container
  links:
    - db
  ports:
    - "8000:80"
  volumes:
    - ./app:/var/www/html/
db:
  image: mysql
  container_name: mysql-container
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: io
    MYSQL_USER: user
    MYSQL_PASSWORD: io
    MYSQL_DATABASE: myapp
    TERM: linux
  volumes:
    - ./data/db:/var/lib/mysql


#docker exec -ti web bash

